trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOTNET_VERSION: '9.0.304'
  AZURE_WEBAPP_NAME: 'dotnet-webapp'
  AZURE_SUBSCRIPTION: 'ADO -AZURE'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK $(DOTNET_VERSION)'
    inputs:
      packageType: 'sdk'
      version: '$(DOTNET_VERSION)'
      includePreview: true

  - script: dotnet --info
    displayName: 'Verify .NET SDK installation'

  - script: dotnet build --configuration Release
    displayName: 'Build project'

  - script: dotnet run --configuration Release
    displayName: 'Run project'
  
  - script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
    displayName: 'Publish Project'
  
  - task: ArchiveFiles@2
    displayName: 'archive publushed files'
    inputs:
     rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
     includeRootFolder: false
     archiveType: 'zip'
     archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'container'

  - task: AzureWebApp@1
    displayName: 'Deploy to App Service'
    inputs:
     azureSubscription: '$(AZURE_SUBSCRIPTION)'
     appName: '$(AZURE_WEBAPP_NAME)'
     package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'